# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ZYIQKeyboardManagerDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ZYIQKeyboardManagerDemo
  pod 'IQKeyboardManager'

  target 'ZYIQKeyboardManagerDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ZYIQKeyboardManagerDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
