# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'DrawEChartDemo' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for DrawEChartDemo
  pod 'iOS-Echarts'

  target 'DrawEChartDemoTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'DrawEChartDemoUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
